version: '3.8'
services:
  # Define the network function to be scaled
  skeleton:
    image: "cont_nf_test:latest"
    volumes:
      - /tmp/rx/{{.Task.Slot}}:/rx_pipe
      - /tmp/tx/{{.Task.Slot}}:/tx_pipe
    working_dir: /container
    command: ./cont_nf
